import { ISetting, SettingType } from '@rocket.chat/apps-engine/definition/settings';

import { EXTERNAL_COMPONENT, SETTINGS } from './constants';

export const settings: Array<ISetting> = [
    {
        id: SETTINGS.LOGS_SOURCE_MODE,
        type: SettingType.STRING,
        packageValue: 'loki',
        required: true,
        public: false,
        i18nLabel: 'Logs source mode',
        i18nDescription: 'Logs data source mode: loki (default) or app_logs (Rocket.Chat app lifecycle logs API).',
    },
    // Loki connection and default query behavior.
    {
        id: SETTINGS.LOKI_BASE_URL,
        type: SettingType.STRING,
        packageValue: '',
        required: true,
        public: false,
        i18nLabel: 'Loki base URL',
        i18nDescription: 'Base URL of your Loki endpoint (for example https://loki.example.com).',
    },
    {
        id: SETTINGS.LOKI_USERNAME,
        type: SettingType.STRING,
        packageValue: '',
        required: false,
        public: false,
        i18nLabel: 'Loki username',
        i18nDescription: 'Optional username used for Loki authentication.',
    },
    {
        id: SETTINGS.LOKI_TOKEN,
        type: SettingType.PASSWORD,
        packageValue: '',
        required: false,
        public: false,
        i18nLabel: 'Loki token or password',
        i18nDescription: 'Optional API token or password used by backend requests to Loki.',
    },
    {
        id: SETTINGS.REQUIRED_LABEL_SELECTOR,
        type: SettingType.STRING,
        packageValue: '{job="rocketchat"}',
        required: true,
        public: false,
        i18nLabel: 'Required label selector',
        i18nDescription: 'Base Loki selector enforced on every query (for example {job="rocketchat",env="prod"}).',
    },
    {
        id: SETTINGS.ALLOWED_ROLES,
        type: SettingType.STRING,
        packageValue: 'admin',
        required: true,
        public: false,
        i18nLabel: 'Allowed roles',
        i18nDescription: 'Comma-separated role names allowed to use logs endpoints (for example admin,log-viewer).',
    },
    {
        id: SETTINGS.WORKSPACE_PERMISSION_CODE,
        type: SettingType.STRING,
        packageValue: 'view-logs',
        required: true,
        public: false,
        i18nLabel: 'Workspace RBAC permission',
        i18nDescription: 'Rocket.Chat permission id to check when RBAC permission mode is enabled (for example view-logs).',
    },
    {
        id: SETTINGS.WORKSPACE_PERMISSION_MODE,
        type: SettingType.STRING,
        packageValue: 'strict',
        required: true,
        public: false,
        i18nLabel: 'Workspace RBAC permission mode',
        i18nDescription: 'Authorization mode: strict (recommended default), fallback (permission check when available, else roles), off (roles only).',
    },
    {
        id: SETTINGS.ENABLE_REDACTION,
        type: SettingType.BOOLEAN,
        packageValue: true,
        required: true,
        public: false,
        i18nLabel: 'Enable log redaction',
        i18nDescription: 'Mask likely sensitive data (tokens, secrets, auth headers) before returning log lines.',
    },
    {
        id: SETTINGS.REDACTION_REPLACEMENT,
        type: SettingType.STRING,
        packageValue: '[REDACTED]',
        required: true,
        public: false,
        i18nLabel: 'Redaction replacement',
        i18nDescription: 'Replacement text used when sensitive patterns are masked.',
    },
    {
        id: SETTINGS.DEFAULT_TIME_RANGE,
        type: SettingType.STRING,
        packageValue: '15m',
        required: true,
        public: false,
        i18nLabel: 'Default time range',
        i18nDescription: 'Default query time range for the logs viewer (for example 15m, 1h, 24h).',
    },
    {
        id: SETTINGS.MAX_TIME_WINDOW_HOURS,
        type: SettingType.NUMBER,
        packageValue: 24,
        required: true,
        public: false,
        i18nLabel: 'Max time window (hours)',
        i18nDescription: 'Maximum allowed query window in hours.',
    },
    {
        id: SETTINGS.MAX_LINES_PER_QUERY,
        type: SettingType.NUMBER,
        packageValue: 2000,
        required: true,
        public: false,
        i18nLabel: 'Max lines per query',
        i18nDescription: 'Upper bound of log lines returned by a single query.',
    },
    {
        id: SETTINGS.QUERY_TIMEOUT_MS,
        type: SettingType.NUMBER,
        packageValue: 30000,
        required: true,
        public: false,
        i18nLabel: 'Query timeout (ms)',
        i18nDescription: 'Timeout applied to Loki HTTP requests in milliseconds.',
    },
    {
        id: SETTINGS.RATE_LIMIT_QPM,
        type: SettingType.NUMBER,
        packageValue: 60,
        required: true,
        public: false,
        i18nLabel: 'Rate limit (queries per minute)',
        i18nDescription: 'Maximum number of query requests per minute per user.',
    },
    {
        id: SETTINGS.AUDIT_RETENTION_DAYS,
        type: SettingType.NUMBER,
        packageValue: 90,
        required: true,
        public: false,
        i18nLabel: 'Audit retention (days)',
        i18nDescription: 'How long query audit entries are retained.',
    },
    {
        id: SETTINGS.AUDIT_MAX_ENTRIES,
        type: SettingType.NUMBER,
        packageValue: 5000,
        required: true,
        public: false,
        i18nLabel: 'Audit max entries',
        i18nDescription: 'Maximum number of in-app audit entries retained.',
    },
    // This URL backs the registered External Component entrypoint.
    {
        id: SETTINGS.EXTERNAL_COMPONENT_URL,
        type: SettingType.STRING,
        packageValue: EXTERNAL_COMPONENT.DEFAULT_URL,
        required: true,
        public: false,
        i18nLabel: 'External component URL',
        i18nDescription: 'URL used by the registered External Component. Use your hosted UI URL for production.',
    },
];
